### ISSUE TITLE
Maj?

### ISSUE THREAD

**Issue by JeromeDesseaux** [cozy-labs/cozy-torrent#3]
Bonjour, 

Où en est le projet? PR acceptées?

Merci

**Comment by nono** [comment]
Bonjour,

le projet est mort. Il avait été démarré par un de nos stagiaires dans le but de proposer ça comme sujet pour l'école 42. Nous avons dû changer d'idée en cours de route et ce projet n'a pas été très loin.

**Comment by JeromeDesseaux** [comment]
Je vois ça... 

Une alternative existe? Sinon je pars from scratch :)
